manifest-version = 1

[component]
name = "ClickHouse"
version = "1.0.0"

category = "data-collection"
subcategory = "warehouse"
language = "Rust"
wit-version = "1.0.0"
documentation = "https://www.edgee.cloud/docs/components/data-collection/clickhouse"
repository = "https://github.com/edgee-cloud/clickhouse-component"
icon-path = "clickhouse-icon.png"
description = '''
# ClickHouse Component

[https://www.edgee.cloud/edgee/clickhouse](https://www.edgee.cloud/edgee/clickhouse)

## Overview

The **ClickHouse** component by Edgee enables fast, edge-native analytics by streaming events directly to your ClickHouse data warehouse.
ClickHouse is a high-performance, columnar OLAP database engineered for rapid queries, large-scale data aggregation, and real-time analytics.
Edgee handles all the streaming logic at the edge—no SDK needed, and no client-side performance hit.

---

## Key Features & Benefits

### Features

- **Edge Event Streaming**: Collects analytics events at the edge and forwards them to ClickHouse.
- **Broad Compatibility**: Works with all ClickHouse endpoints, including ClickHouse Cloud and Aiven.
- **High-Throughput Support**: Supports high-throughput data ingestion for large-scale analytics.
- **Seamless Edgee Integration**: Integrates seamlessly with other Edgee components for comprehensive data workflows.

### Benefits

- **Scalability**: Leverage ClickHouse's scalable infrastructure to handle large volumes of data.
- **Performance**: Achieve low-latency data processing by collecting events at the edge.
- **Integration**: Easily integrate with other Edgee components and analytics tools.

---

## Use Cases

- **Real-Time Analytics**: Collect and analyze data in real-time to make informed decisions.
- **Data Warehousing**: Store and manage large datasets efficiently in ClickHouse.
- **Business Intelligence**: Integrate with BI tools to visualize and interpret data insights.

---

Additional resources:
- [ClickHouse](https://clickhouse.com/)
- [Aiven for ClickHouse](https://aiven.io/clickhouse)
'''


[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && rm -f ./clickhouse.wasm && mv ./target/wasm32-wasip2/release/clickhouse_component.wasm ./clickhouse.wasm"
output_path = "clickhouse.wasm"

[component.settings.endpoint]
title = "Endpoint"
type = "string"
required = true
description = "Your ClickHouse endpoint, including protocol, hostname, and port."

[component.settings.database]
title = "Database"
type = "string"
description = "Your ClickHouse database name ('default' is used if not provided)."

[component.settings.table]
title = "Table"
type = "string"
required = true
description = "Your ClickHouse table name."

[component.settings.username]
title = "Username"
type = "string"
description = "Your ClickHouse username ('default' is used if not provided)."

[component.settings.password]
title = "Password"
type = "string"
required = true
secret = true
description = "Your ClickHouse password."
